import { useRouter } from "next/router";
import Head from 'next/head'
import styles from '../../styles/Game.module.css'
import useSWR from 'swr';
import { useState } from "react";

const fetcher = (url) => fetch(url).then((res) => res.json());

// Grab route param to persist as a prop
export async function getServerSideProps(context) {
    const gameId = context.query.id
    console.log(gameId)
    return {
      props: {gameId}, 
    }
  }

export default function Game({gameId}) {
    const [attendance, setAttendance] = useState("")
    const router = useRouter()

    const { data, error } = useSWR('../api/staticdata', fetcher);
    // Handle error state
    if (error) return <div>Failed to load</div>;
    // Handle loading state
    if (!data) return <div>Loading...</div>;

    const gameArray = JSON.parse(data);

    let gameData;

    for (let i = 0; i < gameArray.length; i++) {
        if (gameArray[i].id == gameId) {
            gameData = gameArray[i]
        }
    }

    function handleClick(value) {
        // console.log(value);
        setAttendance(value)
        console.log(attendance)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <main className={styles.main}>
                <div className={styles.header}>
                    <h1>{ gameData.day } { gameData.sport }</h1> 
                    <p>{gameData.teamAway} @ {gameData.teamHome}</p>
                    <p>{ gameData.location }</p>
                </div>
                <div className={styles.attendancebar}>
                    <button 
                        // className={this.state.active ? 'your_className': null}
                        onClick={() => handleClick('Going')} 
                        className={styles.button}
                    >👍 Going</button>
                    <button onClick={handleClick} className={styles.button}>❓ Maybe</button>
                    <button onClick={handleClick} className={styles.button}>👎 Can't go</button>
                </div>
            </main>
        </div>
    )
}

