import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Calendar.module.css'
import 'react-calendar/dist/Calendar.css';

import { Calendar } from "react-multi-date-picker";
// import Calendar from 'react-calendar';

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Calendar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          {/* <div className={styles.topbar}> */}
            {/* <Image src="/icon-calendar.svg" layout="fixed" width='32px' height='32px'/> */}
            <h1>Your Schedule</h1>
          {/* </div> */}
          {/* <div> */}
          <div className={styles.calendarcontainer}>
            <Calendar 
              className={styles.calendar}
              readOnly={true}
              // disabled={true}
              value={[new Date(2022, 8, 13), new Date(2022, 8, 20)]} 
            />
            </div>
          {/* </div> */}
          <div className={styles.game}>
            <h2>july wtv</h2>
            <p>SMC @ bingbong</p>
          </div>
        </main>
      </div>
    )
  }
  