import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Calendar.module.css'

// import { Calendar, DatePicker } from "react-multi-date-picker";
import Calendar from 'react-calendar';

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          {/* <div className={styles.topbar}> */}
            {/* <Image src="/icon-calendar.svg" layout="fixed" width='32px' height='32px'/> */}
            <h1>Your Schedule</h1>
          {/* </div> */}
          {/* <div> */}
            <Calendar 
              className={styles.calendar}
              
              value={new Date(2022, 7, 8)} 
            />
          {/* </div> */}
          <div className={styles.game}>
            <h2>july wtv</h2>
            <p>SMC @ bingbong</p>
          </div>
        </main>
      </div>
    )
  }
  