import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import useSWR from 'swr';

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {

  const { data, error } = useSWR('./api/staticdata', fetcher);
  // Handle error state
  if (error) return <div>Failed to load</div>;
  // Handle loading state
  if (!data) return <div>Loading...</div>;

  const gameArray = JSON.parse(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Upcoming Games
        </h1>
        <div className={styles.grid}>
      {/* TODO: Pull game data and dynamically create cards */}

          {gameArray.map((game)=>{
              return (
                <Link href={{
                    pathname: `games/[id]`,
                    query: { id: game.id }}
                  }>
                  <div className={styles.card}>
                    <h2>{game.day} {game.sport} &rarr;</h2>
                    <p>{game.teamAway} @ {game.teamHome}</p>
                    <p>{game.location}</p>
                  </div>
              </Link>
            )})}

          {/* <Link href={`/games/lol`}>
          <div className={styles.card}>
            <h2>Aug 14 🏀 &rarr;</h2>
            <p>UC @ New College</p>
            <p>Athletic Centre Court 4</p>
          </div>
          </Link>
 
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Aug 16 🏐  &rarr;</h2>
            <p>SMC @ UC</p>
            <p>Athletic Centre Multi Sports Hall</p>
          </a> */}
        </div>

        <h1>
          Your Teams
        </h1>
        <div className={styles.teamgrid}>
          <a href="https://nextjs.org/docs" className={styles.teamcard}>
            <h2>UC 🏀</h2>
            <p>Division 1</p>
            <p>4-1-0, 2nd place</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.teamcard}>
            <h2>SMC 🏐</h2>
            <p>Division 1</p>
            <p>5-0-0, 1st place</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.teamcard}>
            <h2>UC 🥏</h2>
            <p>Division 2</p>
            <p>2-3-0, 3rd place</p>
          </a>
        </div>
      </main>
    </div>
  )
}
