import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Upcoming Games
        </h1>
      {/* TODO: Pull game data and dynamically create cards */}
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>🏀 Aug 14 &rarr;</h2>
            <p>UC @ New College</p>
            <p>Athletic Centre Court 4</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>🏐 Aug 16 &rarr;</h2>
            <p>SMC @ UC</p>
            <p>Athletic Centre Multi Sports Hall</p>
          </a>

        </div>
        <h1>
          Stats
        </h1>


      </main>

      
    </div>
  )
}
