import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Profile.module.css'

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Proflie</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
            <div className={styles.profilepic}>
              <Image className={styles.profilepic} src="/hudson-headshot.jpeg" width={90} height={90}/>
            </div>
            <h1>Hudson</h1>

            <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Aug 14 🏀 &rarr;</h2>
            <p>UC @ New College</p>
            <p>Athletic Centre Court 4</p>
          </a>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Aug 16 🏐  &rarr;</h2>
            <p>SMC @ UC</p>
            <p>Athletic Centre Multi Sports Hall</p>
          </a>
        </div>
        </main>
      </div>
    )
  }
  