import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Profile.module.css'

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Profile</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <div className={styles.profilepic}>
            <Image className={styles.profilepic} src="/hudson-headshot.jpeg" width={110} height={110}/>
          </div>
          <h1>Hudson</h1>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>312</h2>
              <p>games played</p>
            </a>
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>3</h2>
              <p>championships</p>
            </a>
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>17</h2>
              <p>ejections</p>
            </a>
            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>4</h2>
              <p>foul outs</p>
            </a>
          </div>
        </main>
      </div>
    )
  }
  